routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');
Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('auth')->group(function(){
    Route::get('/','AdminController@index')->name('index');
    Route::get('/pegawai','AdminController@pegawai')->name('pegawai.index');
    Route::get('/pegawai/tambah','AdminController@tambah')->name('pegawai.tambah');
    Route::post('pegawai/tambah','AdminController@store')->name('pegawai.store');
    Route::post('pegawai/tambah','AdminController@store')->name('pegawai.store');
    Route::put('/pegawai/{id}/update', 'AdminController@update')->name('pegawai.update');
    Route::get('/pegawai/{id}/edit','AdminController@edit')->name('pegawai.edit');
    Route::get('/pegawai/{id}/delete','AdminController@delete')->name('pegawai.delete');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/AdminController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DB;
use App\Admin\Employee;

class AdminController extends Controller
{
    //

    public function index()
    {
       
        $l = Employee::where('jenis_kelamin','l')->count();
        $p = Employee::where('jenis_kelamin','p')->count();
        $ageR = DB::table('employees')->select(DB::raw("
        case
          when datediff(now(), tanggal_lahir) / 365.25 > 50 then '51+'
          when datediff(now(), tanggal_lahir) / 365.25 > 30 then '31-50'                                     
          when datediff(now(), tanggal_lahir) / 365.25 > 19 then '10-30'                                     
          else '1-20'
      end as age_group
      "))->get();
      $a = 0;
      $b = 0;
      $c = 0;
      $d=0;
      foreach ($ageR as $key) {
          if($key->age_group=='51+'){
              $a++;
          }elseif ($key->age_group=='31-50') {
              $b++;
          }elseif ($key->age_group=='10-30') {
              $c++;
          }else{
              $d++;
          }
      }
        return view('admin.index')->with(['l'=>$l,'p'=>$p,'a'=>$a,'b'=>$b,'c'=>$c,'d'=>$d]);
    }

    public function pegawai()
    {
        # code...
        $employees = Employee::all();
        
        return view('admin.pegawai.index')->with('employees',$employees);
    }

    public function tambah()
    {
        # code...
        return view('admin.pegawai.tambah');
    }

    public function edit($id)
    {
        # code...
        $employee = Employee::findOrFail($id);
        return view('admin.pegawai.edit')->with('employee',$employee);
    }
    public function store(Request $request)
    {
        # code...
        $pegawai = new Employee;
        $pegawai->nama = $request->nama;
        $pegawai->tempat_lahir = $request->tempat_lahir;
        $pegawai->tanggal_lahir = $request->tanggal_lahir;
        $pegawai->jenis_kelamin = $request->jk;
        $pegawai->alamat = $request->alamat;
        $pegawai->save();
        return redirect()->route('admin.pegawai.index');
    }

    public function delete($id)
    {
        
            $em = Employee::findOrFail($id);
            $em->delete();
            return redirect()->route('admin.pegawai.index');
    }

    public function update($id, Request $request){
        $pegawai = Employee::findOrFail($id);
        $pegawai->nama = $request->nama;
        $pegawai->tempat_lahir = $request->tempat_lahir;
        $pegawai->tanggal_lahir = $request->tanggal_lahir;
        $pegawai->jenis_kelamin = $request->jk;
        $pegawai->alamat = $request->alamat;
        $pegawai->save();
        return redirect()->route('admin.pegawai.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/admin/index.blade.php
@extends('layouts.admin')
@section('content')
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">Dashboard</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item active"><a href="#">Home</a></li>

        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
  <div class="container-fluid">
    <!-- Small boxes (Stat box) -->
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            <div class="d-flex justify-content-between align-items-center">
              <h5 class="card-title">Statistik Pegawai</h5>
              <a href="{{route('admin.pegawai.index')}}" class="btn btn-info btn-sm"> Lihat Data </a>
            </div>
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            <div class="row">
              <div class="col-md-5">
                <p class="text-center">
                  <strong>Jenis Kelamin</strong>
                </p>
                <canvas id="pieChart"
                  style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></canvas>
              </div>
              <!-- /.col -->
              <div class="col-md-7">
                <p class="text-center">
                  <strong>Usia</strong>
                </p>



                <canvas id="barChart"
                  style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></canvas>
              </div>
              <!-- /.col -->
            </div>
            <!-- /.row -->
          </div>
          <!-- ./card-body -->

        </div>
        <!-- /.card -->
      </div>
    </div>
    <!-- /.row -->

  </div><!-- /.container-fluid -->
</section>

<!-- /.content -->
@endsection

@section('script')
<script>
  //- PIE CHART -
    //-------------
    // Get context with jQuery - using jQuery's .get() method.
    var pieChartCanvas = $('#pieChart').get(0).getContext('2d')
    var pieData        = {
      labels: [
          'Laki-laki', 
          'Perempuan'
          
      ],
      datasets: [
        {
          data: [{{$l}},{{$p}}],
          backgroundColor : ['#f56954', '#00a65a'],
        }
      ]
    }
    var pieOptions     = {
      maintainAspectRatio : false,
      responsive : true,
      segmentShowStroke: true,
      segmentStrokeColor: "#fff",
      segmentStrokeWidth: 2,
      percentageInnerCutout: 0,
      animationSteps: 100,  
      animationEasing: "easeOutBounce",
      animateRotate: true,
    }
    //Create pie or douhnut chart
    var pieChart = new Chart(pieChartCanvas, {
      type: 'pie',
      data: pieData,
      options: pieOptions      
    })

    //- BAR CHART -
    //-------------
    
    var barChartCanvas = $('#barChart').get(0).getContext('2d')
    var barChartData = {labels  : ['50+', '30-50', '10-30',  '0-10'],
      datasets: [
        {
          label               : 'Rentang Usia',
          backgroundColor     : 'rgba(60,141,188,0.9)',
          borderColor         : 'rgba(60,141,188,0.8)',
          pointRadius          : false,
          pointColor          : '#3b8bba',
          pointStrokeColor    : 'rgba(60,141,188,1)',
          pointHighlightFill  : '#fff',
          pointHighlightStroke: 'rgba(60,141,188,1)',
          data                : [{{$a}}, {{$b}}, {{$c}},{{$d}}]
        }]} 
    
    var barChartOptions = {
      responsive              : true,
      maintainAspectRatio     : false,
      datasetFill             : false
    }

    var barChart = new Chart(barChartCanvas, {
      type: 'bar', 
      data: barChartData,
      options: barChartOptions
    })
</script>
@endsection

resources/views/admin/pegawai/edit.blade.php
@extends('layouts.admin')
@section('content')
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Dashboard</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Dashboard v1</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <!-- Main row -->
        <div class="row">
            <!-- Left col -->
            <section class="col-lg-12 col-sm-12 col-12">
                <!-- Custom tabs (Charts with tabs)-->
                <div class="card">
                    <div class="card-header">
                        <div class="d-flex justify-content-between align-items-center">
                            <h3 class="card-title">
                                Pegawai
                            </h3>
                            {{-- <a class="btn btn-info btn-sm float-right" href="{{route('admin.user.tambah')}}"> +
                            Tambah</a> --}}
                            <button type="button" class="btn btn-info btn-sm float-right" data-toggle="modal"
                                data-target="#modal-tambah"> + Tambah</button>
                        </div>

                    </div><!-- /.card-header -->
                    <div class="card-body">

                        <form method="post" action="{{route('admin.pegawai.update',$employee->id)}}">
                            @csrf
                            {{ method_field('PUT') }}
                            <div class="form-group">
                                <label for="Nama">Nama</label>
                                <input type="text" name="nama" class="form-control" id="nama" placeholder="Nama Pegawai"
                                    value="{{$employee->nama}}">
                            </div>
                            <div class="form-group">
                                <label for="tptLahir">Tempat Lahir</label>
                                <input type="text" name="tempat_lahir" class="form-control" id="tempat_lahir"
                                    placeholder="Tempat Lahir" value="{{$employee->tempat_lahir}}">
                            </div>
                            <div class="form-group">
                                <label for="tglLahir">Tanggal Lahir</label>
                                <input type="date" name="tanggal_lahir" class="form-control" id="tanggal_lahir"
                                    placeholder="1970-06-19" value="{{$employee->tanggal_lahir}}"></div>

                            <div class="form-group">
                                <label for="jk">Jenis Kelamin</label>
                                <select name="jk" class="custom-select">
                                    <option value="l">Laki-laki</option>
                                    <option value="p">Perempuan</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="alamat">Alamat</label>
                                <input type="text" name="alamat" class="form-control" id="alamat" placeholder="Alamat"
                                    value="{{$employee->alamat}}">
                            </div>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    </div>
                </div>
                <!-- /.card -->

            </section>
            <!-- /.Left col -->
        </div>
        <!-- /.row (main row) -->
    </div><!-- /.container-fluid -->
</section>


@endsection

resources/views/admin/pegawai/index.blade.php
@extends('layouts.admin')
@section('content')
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Dashboard</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Dashboard v1</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <!-- Main row -->
        <div class="row">
            <!-- Left col -->
            <section class="col-lg-12 col-sm-12 col-12">
                <!-- Custom tabs (Charts with tabs)-->
                <div class="card">
                    <div class="card-header">
                        <div class="d-flex justify-content-between align-items-center">
                            <h3 class="card-title">
                                Pegawai
                            </h3>
                            <a class="btn btn-info btn-sm float-right" href="{{route('admin.pegawai.tambah')}}"> +
                                Tambah</a>
                            {{-- <button type="button" class="btn btn-info btn-sm float-right" data-toggle="modal"
                                data-target="#modal-tambah"> + Tambah</button> --}}
                        </div>

                    </div><!-- /.card-header -->
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-hover dataTable" role="grid"
                            aria-describedby="example2_info">
                            <thead>
                                <tr role="row">
                                    <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1"
                                        colspan="1" aria-sort="ascending" aria-label="#">#</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Nama">
                                        Nama</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Usia">
                                        TTL</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Usia">
                                        Usia</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Jenis Kelamin">
                                        Jenis Kelamin</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Alamat">
                                        Alamat</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Action">
                                        Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($employees as $employee)

                                <tr role="row">
                                    <td>{{$loop->iteration}}</td>
                                    <td>{{$employee->nama}}</td>
                                    <td>{{$employee->tempat_lahir.', '.tgl_indo($employee->tanggal_lahir)}}
                                    </td>
                                    <td>{{$employee->getAge()}}</td>
                                    <td>{{$employee->jenis_kelamin == 'l' ? "Laki-laki" : "Perempuan"}}</td>
                                    <td>{{$employee->alamat}}</td>
                                    <td><a class="btn btn-warning btn-sm"
                                            href="{{route('admin.pegawai.edit',$employee->id)}}">Edit</a>
                                        <a href="{{route('admin.pegawai.delete',$employee->id)}}"
                                            class="btn btn-danger btn-sm">Hapus</a></td>
                                </tr>
                                @endforeach

                            </tbody>
                        </table>
                    </div><!-- /.card-body -->
                </div>
                <!-- /.card -->

            </section>
            <!-- /.Left col -->
        </div>
        <!-- /.row (main row) -->
    </div><!-- /.container-fluid -->
</section>
<?php
function tgl_indo($tanggal){
	$bulan = array (
		1 =>   'Januari',
		'Februari',
		'Maret',
		'April',
		'Mei',
		'Juni',
		'Juli',
		'Agustus',
		'September',
		'Oktober',
		'November',
		'Desember'
	);
	$pecahkan = explode('-', $tanggal);
	
	// variabel pecahkan 0 = tanggal
	// variabel pecahkan 1 = bulan
	// variabel pecahkan 2 = tahun
 
	return $pecahkan[2] . ' ' . $bulan[ (int)$pecahkan[1] ] . ' ' . $pecahkan[0];
}
?>
{{-- @include('admin.pegawai.modal_tambah') --}}
<!-- /.content -->
@endsection
@section('script')
<script>
    $(function () {
    $("#example2").DataTable();
    $('#example1').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": true,
      "ordering": true,
      "info": true,
      "autoWidth": false,
    });
  });

  function fetchData() {
    $.ajax({
        url: "",
        method: "get",
        success: function(res){
          console.log(res);
        }
      })
  }
  toastr.options = {
  "closeButton": true,
  "debug": false,
  "newestOnTop": false,
  "progressBar": true,
  "positionClass": "toast-top-right",
  "preventDuplicates": false,
  "onclick": null,
  "showDuration": "300",
  "hideDuration": "1000",
  "timeOut": "5000",
  "extendedTimeOut": "1000",
  "showEasing": "swing",
  "hideEasing": "linear",
  "showMethod": "fadeIn",
  "hideMethod": "fadeOut"
}

</script>
@endsection

resources/views/admin/pegawai/tambah.blade.php
@extends('layouts.admin')
@section('content')
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Dashboard</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Pegawai</a></li>
                    <li class="breadcrumb-item active">Tambah</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <!-- Main row -->
        <div class="row">
            <!-- Left col -->
            <section class="col-lg-12 col-sm-12 col-12">
                <!-- Custom tabs (Charts with tabs)-->
                <div class="card">
                    <div class="card-header">
                        <div class="d-flex justify-content-between align-items-center">
                            <h3 class="card-title">
                                Pegawai
                            </h3>
                            {{-- <a class="btn btn-info btn-sm float-right" href="{{route('admin.user.tambah')}}"> +
                            Tambah</a> --}}
                            <button type="button" class="btn btn-info btn-sm float-right" data-toggle="modal"
                                data-target="#modal-tambah"> + Tambah</button>
                        </div>

                    </div><!-- /.card-header -->
                    <div class="card-body">

                        <form method="post" action="{{route('admin.pegawai.store')}}">
                            @csrf
                            <div class="form-group">
                                <label for="Nama">Nama</label>
                                <input type="text" name="nama" class="form-control" id="nama"
                                    placeholder="Nama Pegawai">
                            </div>
                            <div class="form-group">
                                <label for="tptLahir">Tempat Lahir</label>
                                <input type="text" name="tempat_lahir" class="form-control" id="tempat_lahir"
                                    placeholder="Tempat Lahir" onblur="tgl()">
                            </div>
                            <div class="form-group">
                                <label for="tglLahir">Tanggal Lahir</label>
                                <input type="date" name="tanggal_lahir" class="form-control" id="tanggal_lahir"
                                    placeholder="1970-06-19" onchange="hitUsia()" </div> <div class="form-group">
                                <label for="Nama">Usia</label>
                                <input type="int" name="usia" class="form-control" id="usia" placeholder="Usia Anda">
                            </div>
                            <div class="form-group">
                                <label for="jk">Jenis Kelamin</label>
                                <select name="jk" class="custom-select">
                                    <option value="l">Laki-laki</option>
                                    <option value="p">Perempuan</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="alamat">Alamat</label>
                                <input type="text" name="alamat" class="form-control" id="alamat" placeholder="Alamat">
                            </div>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    </div>
                </div>
                <!-- /.card -->

            </section>
            <!-- /.Left col -->
        </div>
        <!-- /.row (main row) -->
    </div><!-- /.container-fluid -->
</section>

<script>
    function hitUsia() {  
        var dob = $('#tanggal_lahir').val();
        dob = new Date(dob);
        var today = new Date();
        var age = Math.floor((today-dob) / (365.25 * 24 * 60 * 60 * 1000));
        console.log(age);
        $('#usia').val(age+' Tahun');
    }
</script>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/admin_sidebar.blade.php
<!-- Main Sidebar Container -->
<aside class="main-sidebar elevation-4 sidebar-light-info">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link navbar-light">
        <img src="{{asset('dist/img/AdminLTELogo.png')}}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
            style="opacity: .8">
        <span class="brand-text font-weight-light">AdminLTE 3</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{asset('dist/img/user2-160x160.jpg')}}" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">{{Auth::user()->name}}</a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                 with font-awesome or any other icon font library -->
                <li class="nav-item has-treeview">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Dashboard
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="./index.html" class="nav-link active">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Dashboard v1</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="./index2.html" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Dashboard v2</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="./index3.html" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Dashboard v3</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li
                    class="nav-item has-treeview {{request()->is('admin/users') || request()->is('admin/user*')  ? 'menu-open' : null }}">
                    <a href="#"
                        class="nav-link {{request()->is('admin/users') || request()->is('admin/user*') ? 'active' : ''}}">
                        <i class="nav-icon fas fa-users"></i>
                        <p>
                            Manage Users
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="/"
                                class="nav-link {{request()->is('admin/users') || request()->is('admin/user*') ? 'active' : ''}}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Daftar User</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li
                    class="nav-item has-treeview {{request()->is('admin/industri') || request()->is('admin/industri*')  ? 'menu-open' : null }}">
                    <a href="#"
                        class="nav-link {{request()->is('admin/industri') || request()->is('admin/industri*') ? 'active' : ''}}">
                        <i class="nav-icon fas fa-users"></i>
                        <p>
                            Manage Industri
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="/"
                                class="nav-link {{request()->is('admin/industri') || request()->is('admin/industri*') ? 'active' : ''}}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Daftar Industri</p>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="nav-header">Account</li>
                <li class="nav-item">
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                    <a href="{{ route('logout') }}" class="nav-link" onclick="event.preventDefault();
                                                       document.getElementById('logout-form').submit();">
                        <i class="nav-icon far fa-circle text-danger"></i>
                        <p class="text">Logout</p>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>